[2024-02-11 20:11:07,036] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: fetch_data.is_api_available 2024-02-11T20:11:05.678144+00:00 [queued]>
[2024-02-11 20:11:07,043] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: fetch_data.is_api_available 2024-02-11T20:11:05.678144+00:00 [queued]>
[2024-02-11 20:11:07,044] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2024-02-11 20:11:07,044] {taskinstance.py:1069} INFO - Starting attempt 1 of 3
[2024-02-11 20:11:07,044] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2024-02-11 20:11:07,057] {taskinstance.py:1089} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-02-11T20:11:05.678144+00:00
[2024-02-11 20:11:07,061] {standard_task_runner.py:52} INFO - Started process 377 to run task
[2024-02-11 20:11:07,064] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_data', 'is_api_available', '2024-02-11T20:11:05.678144+00:00', '--job-id', '6', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/fetch_data.py', '--cfg-path', '/tmp/tmphscvxpqd', '--error-file', '/tmp/tmpkla_l8nv']
[2024-02-11 20:11:07,065] {standard_task_runner.py:77} INFO - Job 6: Subtask is_api_available
[2024-02-11 20:11:07,107] {logging_mixin.py:104} INFO - Running <TaskInstance: fetch_data.is_api_available 2024-02-11T20:11:05.678144+00:00 [running]> on host 7ce64847329b
[2024-02-11 20:11:07,160] {taskinstance.py:1281} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=fetch_data
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2024-02-11T20:11:05.678144+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-11T20:11:05.678144+00:00
[2024-02-11 20:11:07,161] {http.py:122} INFO - Poking: /pjp-api/rest/station/findAll
[2024-02-11 20:11:07,171] {base.py:69} INFO - Using connection to: id: fetch_data_gov. Host: https://api.gios.gov.pl/, Port: None, Schema: , Login: , Password: None, extra: None
[2024-02-11 20:11:09,647] {http.py:122} INFO - Poking: /pjp-api/rest/station/findAll
[2024-02-11 20:11:09,657] {base.py:69} INFO - Using connection to: id: fetch_data_gov. Host: https://api.gios.gov.pl/, Port: None, Schema: , Login: , Password: None, extra: None
[2024-02-11 20:11:12,251] {http.py:122} INFO - Poking: /pjp-api/rest/station/findAll
[2024-02-11 20:11:12,282] {base.py:69} INFO - Using connection to: id: fetch_data_gov. Host: https://api.gios.gov.pl/, Port: None, Schema: , Login: , Password: None, extra: None
[2024-02-11 20:11:14,764] {http.py:122} INFO - Poking: /pjp-api/rest/station/findAll
[2024-02-11 20:11:14,774] {base.py:69} INFO - Using connection to: id: fetch_data_gov. Host: https://api.gios.gov.pl/, Port: None, Schema: , Login: , Password: None, extra: None
[2024-02-11 20:11:17,299] {http.py:122} INFO - Poking: /pjp-api/rest/station/findAll
[2024-02-11 20:11:17,315] {base.py:69} INFO - Using connection to: id: fetch_data_gov. Host: https://api.gios.gov.pl/, Port: None, Schema: , Login: , Password: None, extra: None
[2024-02-11 20:11:20,115] {http.py:122} INFO - Poking: /pjp-api/rest/station/findAll
[2024-02-11 20:11:20,133] {base.py:69} INFO - Using connection to: id: fetch_data_gov. Host: https://api.gios.gov.pl/, Port: None, Schema: , Login: , Password: None, extra: None
[2024-02-11 20:11:22,654] {http.py:122} INFO - Poking: /pjp-api/rest/station/findAll
[2024-02-11 20:11:22,677] {base.py:69} INFO - Using connection to: id: fetch_data_gov. Host: https://api.gios.gov.pl/, Port: None, Schema: , Login: , Password: None, extra: None
[2024-02-11 20:11:25,247] {http.py:122} INFO - Poking: /pjp-api/rest/station/findAll
[2024-02-11 20:11:25,260] {base.py:69} INFO - Using connection to: id: fetch_data_gov. Host: https://api.gios.gov.pl/, Port: None, Schema: , Login: , Password: None, extra: None
[2024-02-11 20:11:27,727] {http.py:122} INFO - Poking: /pjp-api/rest/station/findAll
[2024-02-11 20:11:27,737] {base.py:69} INFO - Using connection to: id: fetch_data_gov. Host: https://api.gios.gov.pl/, Port: None, Schema: , Login: , Password: None, extra: None
[2024-02-11 20:11:28,286] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.8/site-packages/airflow/sensors/base.py", line 236, in execute
    raise AirflowSensorTimeout(f"Snap. Time is OUT. DAG id: {log_dag_id}")
airflow.exceptions.AirflowSensorTimeout: Snap. Time is OUT. DAG id: fetch_data
[2024-02-11 20:11:28,287] {taskinstance.py:1525} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_data, task_id=is_api_available, execution_date=20240211T201105, start_date=20240211T201107, end_date=20240211T201128
[2024-02-11 20:11:28,321] {local_task_job.py:146} INFO - Task exited with return code 1
